package com.swcsoftware.valuelens.core

import com.swcsoftware.valuelens.domain.CompanyRef
import com.swcsoftware.valuelens.domain.DataCheck
import com.swcsoftware.valuelens.domain.GrowthEntry
import com.swcsoftware.valuelens.domain.HistoryPoint
import com.swcsoftware.valuelens.domain.Quote
import com.swcsoftware.valuelens.domain.SectorInfo
import com.swcsoftware.valuelens.domain.CoverageReport
import com.swcsoftware.valuelens.domain.ShareClass
import com.swcsoftware.valuelens.domain.SourcedValue
import com.swcsoftware.valuelens.domain.ValuationReport
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

const val DISCLAIMER = "Generated by Alpha • Built on Pure Fundamental SEC EDGAR Disclosures • Not Financial Advice"

/** Assembles the domain ValuationReport from normalized financials — mirrors valuation/engine.py. */
object Report {
    private val SNAPSHOT_KEYS = listOf("revenue", "net_income", "eps_diluted", "cfo", "fcf", "owner_earnings", "equity", "cash",
        "total_debt", "total_liabilities", "total_assets", "roic", "roe", "current_ratio", "debt_to_equity", "operating_margin", "net_margin", "book_value_per_share", "dividends_per_share")

    fun growth(fin: NormalizedFinancials): LinkedHashMap<String, GrowthEntry> =
        LinkedHashMap(Statements.growthSummary(fin).mapValues { (_, g) -> GrowthEntry(g.fullPeriodYears, g.fullPeriodCagr, g.fiveYearCagr) })

    fun history(fin: NormalizedFinancials): List<HistoryPoint> = fin.annual.map { p ->
        HistoryPoint(p.fiscalYear, p.periodEnd.toString(), p.get("revenue"), p.get("net_income"), p.get("eps_diluted"), p.get("fcf"),
            p.get("owner_earnings"), p.get("equity"), p.get("roic"), p.get("book_value_per_share"), p.get("cfo"), p.get("capex"))
    }

    fun build(fin: NormalizedFinancials, a: AssumptionsCore, quote: Quote?, generatedAt: String,
              dataChecks: List<DataCheck> = emptyList(), provenance: Map<String, String> = emptyMap(),
              sector: SectorInfo? = null, shareClasses: List<ShareClass> = emptyList(), coverage: CoverageReport? = null): ValuationReport {
        val price = quote?.price
        val mode = sector?.let { runCatching { SectorMode.valueOf(it.mode.uppercase()) }.getOrNull() } ?: SectorMode.GENERAL
        val modelA = when (mode) { SectorMode.FINANCIAL -> Sector.financialModelA(fin, a, price); SectorMode.REIT -> Sector.reitModelA(fin, a, price); else -> ModelA.run(fin, a, price) }
        val modelB = when (mode) { SectorMode.FINANCIAL -> Sector.financialModelB(fin, a, price); SectorMode.REIT -> Sector.reitModelB(fin, a, price); else -> ModelB.run(fin, a, price) }
        val snapshot = LinkedHashMap<String, SourcedValue>()
        fin.ttm?.let { t -> for (k in SNAPSHOT_KEYS) t.values[k]?.let { snapshot[k] = it.toDomain() } }
        return ValuationReport(
            company = CompanyRef(fin.ticker, fin.cik, fin.name), quote = quote, assumptions = a.toDomain(),
            snapshot = snapshot, history = history(fin), growth = growth(fin),
            modelA = modelA, modelB = modelB,
            warnings = fin.warnings, disclaimer = DISCLAIMER, generatedAt = generatedAt,
            dataChecks = dataChecks, provenance = provenance, sector = sector, shareClasses = shareClasses, coverage = coverage,
        )
    }

    // ---- JSON views matching the Python reference's dict shapes (used by the oracle test and iOS) ----
    fun periodJson(p: PeriodCore): JsonObject = JsonObject(linkedMapOf(
        "label" to JsonPrimitive(p.label), "period_end" to JsonPrimitive(p.periodEnd.toString()),
        "fiscal_year" to (p.fiscalYear?.let { JsonPrimitive(it) } ?: JsonNull), "form" to JsonPrimitive(p.form),
        "values" to JsonObject(p.values.mapValues { svJson(it.value) }),
    ))

    fun svJson(sv: SourcedValueCore): JsonObject = JsonObject(linkedMapOf(
        "value" to JsonPrimitive(sv.value), "tag" to JsonPrimitive(sv.qualifiedTag), "accession" to JsonPrimitive(sv.accession),
        "form" to JsonPrimitive(sv.form), "period_end" to JsonPrimitive(sv.periodEnd.toString()),
        "period_start" to (sv.periodStart?.let { JsonPrimitive(it.toString()) } ?: JsonNull), "filed" to JsonPrimitive(sv.filed.toString()),
        "derived" to JsonPrimitive(sv.derived), "note" to JsonPrimitive(sv.note),
    ))

    fun growthJson(fin: NormalizedFinancials): JsonObject = JsonObject(Statements.growthSummary(fin).mapValues { (_, g) ->
        val m = linkedMapOf<String, JsonElement>("full_period_years" to JsonPrimitive(g.fullPeriodYears), "full_period_cagr" to (g.fullPeriodCagr?.let { JsonPrimitive(it) } ?: JsonNull))
        if (g.hasFive) m["five_year_cagr"] = g.fiveYearCagr?.let { JsonPrimitive(it) } ?: JsonNull
        JsonObject(m)
    })

    fun financialsJson(fin: NormalizedFinancials): JsonObject = JsonObject(linkedMapOf(
        "annual" to JsonArray(fin.annual.map { periodJson(it) }),
        "ttm" to (fin.ttm?.let { periodJson(it) } ?: JsonNull),
        "current_shares" to (fin.currentShares?.let { svJson(it) } ?: JsonNull),
        "growth" to growthJson(fin),
        "warnings" to JsonArray(fin.warnings.map { JsonPrimitive(it) }),
    ))
}
