package com.swcsoftware.valuelens.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.swcsoftware.valuelens.AppState
import com.swcsoftware.valuelens.domain.CompanyRef
import com.swcsoftware.valuelens.domain.SecIdentity
import com.swcsoftware.valuelens.domain.ValuationModel
import com.swcsoftware.valuelens.domain.ValuationReport
import com.swcsoftware.valuelens.domain.metric
import com.swcsoftware.valuelens.domain.result
import com.swcsoftware.valuelens.ui.Fmt
import com.swcsoftware.valuelens.ui.components.Card
import com.swcsoftware.valuelens.ui.components.MarginOfSafetyView
import com.swcsoftware.valuelens.ui.components.MetricRow
import com.swcsoftware.valuelens.ui.components.ModelToggle
import com.swcsoftware.valuelens.ui.components.PrimaryButton
import com.swcsoftware.valuelens.ui.components.ThinDivider
import com.swcsoftware.valuelens.ui.theme.Mono
import com.swcsoftware.valuelens.ui.theme.VL
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

const val DISCLAIMER = "Generated by ValueLens • Built on Pure Fundamental SEC EDGAR Disclosures • Not Financial Advice"

@Composable
fun IdentityScreen(state: AppState, onContinue: () -> Unit) {
    var name by remember { mutableStateOf(state.identity?.fullName ?: "") }
    var email by remember { mutableStateOf(state.identity?.email ?: "") }
    val id = SecIdentity(name, email)
    Column(Modifier.fillMaxSize().background(VL.background).verticalScroll(rememberScrollState()).padding(20.dp)) {
        Spacer(Modifier.height(40.dp))
        Text("ValueLens", style = MaterialTheme.typography.displaySmall, color = VL.textPrimary)
        Text("Intrinsic value from primary SEC disclosures.\nNo charts. No momentum. No noise.", color = VL.textSecondary, modifier = Modifier.padding(top = 8.dp, bottom = 28.dp))
        Card {
            Text("Identify yourself to SEC EDGAR", style = MaterialTheme.typography.titleMedium, color = VL.textPrimary)
            Text("SEC's fair-access policy requires every request to declare who is asking. Your name and email are stored encrypted on this device and sent only as the EDGAR User-Agent header.",
                style = MaterialTheme.typography.bodySmall, color = VL.textSecondary, modifier = Modifier.padding(vertical = 10.dp))
            OutlinedTextField(name, { name = it }, label = { Text("Full name") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(email, { email = it }, label = { Text("Email address") }, singleLine = true, modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Email))
            Text("User-Agent: ${if (id.isValid) id.userAgent else "Jane Doe jane@example.com"}", fontFamily = Mono, fontSize = 12.sp, color = VL.textTertiary, modifier = Modifier.padding(top = 10.dp))
        }
        Spacer(Modifier.height(24.dp))
        PrimaryButton("Continue to guided valuation", enabled = id.isValid) { state.saveIdentity(SecIdentity(name.trim(), email.trim())); onContinue() }
        Text(DISCLAIMER, style = MaterialTheme.typography.bodySmall, color = VL.textTertiary, modifier = Modifier.padding(top = 20.dp).fillMaxWidth())
    }
}

/** Interactive case study: pick a company (preset or any SEC filer) and walk through a live valuation. */
@Composable
fun CaseStudyScreen(state: AppState, onFinished: () -> Unit) {
    val scope = rememberCoroutineScope()
    var report by remember { mutableStateOf<ValuationReport?>(null) }
    var loading by remember { mutableStateOf<String?>(null) }
    var error by remember { mutableStateOf<String?>(null) }
    var query by remember { mutableStateOf("") }
    var results by remember { mutableStateOf<List<CompanyRef>>(emptyList()) }
    var searchJob by remember { mutableStateOf<Job?>(null) }
    val presets = listOf("AAPL" to "Apple", "KO" to "Coca-Cola", "MSFT" to "Microsoft")

    fun load(t: String) {
        loading = t; error = null
        scope.launch {
            runCatching { state.repository.valuation(t, overrides = state.overrides) }
                .onSuccess { report = it }.onFailure { error = it.message }
            loading = null
        }
    }

    val r = report
    if (r != null) { CaseStudyWalkthrough(r, onFinish = { state.addToWatchlist(r); state.updateOnboarded(true); onFinished() }); return }

    Column(Modifier.fillMaxSize().background(VL.background).verticalScroll(rememberScrollState()).padding(20.dp)) {
        Text("Pick a company you know.", style = MaterialTheme.typography.headlineSmall, color = VL.textPrimary)
        Text("We'll pull its 10-K and 10-Q filings straight from SEC EDGAR and value it together, one step at a time.", color = VL.textSecondary, modifier = Modifier.padding(vertical = 10.dp))
        presets.forEach { (t, n) -> CompanyChoice(t, n, loading == t, enabled = loading == null) { load(t) } }
        run {
            Text("…or any other SEC filer", style = MaterialTheme.typography.bodySmall, color = VL.textTertiary, modifier = Modifier.padding(top = 8.dp))
            OutlinedTextField(query, { q ->
                query = q; searchJob?.cancel()
                searchJob = scope.launch { delay(300); results = runCatching { state.repository.search(q) }.getOrDefault(emptyList()) }
            }, label = { Text("Ticker or company name") }, singleLine = true, modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp))
            results.take(6).forEach { c -> CompanyChoice(c.ticker, c.name, loading == c.ticker, enabled = loading == null) { load(c.ticker) } }
        }
        error?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = VL.danger, modifier = Modifier.padding(top = 8.dp)) }
    }
}

@Composable
private fun CompanyChoice(ticker: String, name: String, loading: Boolean, enabled: Boolean, onClick: () -> Unit) {
    Card(Modifier.padding(bottom = 10.dp).clickable(enabled = enabled, onClick = onClick), padding = 14) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Column(Modifier.weight(1f)) { Text(ticker, style = MaterialTheme.typography.titleMedium, color = VL.textPrimary); Text(name, style = MaterialTheme.typography.bodySmall, color = VL.textSecondary, maxLines = 1) }
            if (loading) CircularProgressIndicator(Modifier.width(20.dp).height(20.dp), strokeWidth = 2.dp) else Text("›", color = VL.textTertiary, fontSize = 20.sp)
        }
    }
}

@Composable
private fun CaseStudyWalkthrough(r: ValuationReport, onFinish: () -> Unit) {
    var page by remember { mutableStateOf(0) }
    var model by remember { mutableStateOf(ValuationModel.A) }
    val titles = listOf("Raw 10-K numbers", "Traditional value", "Flip to modern fair value", "Margin of safety")
    val blurbs = listOf(
        "Everything starts from audited statements. These are the trailing-twelve-month figures, each traceable to an XBRL tag in a specific SEC filing.",
        "Graham's formula turns earnings and growth into a price, adjusted for today's bond yields. Buffett's owner earnings ask what cash the business really throws off. Tap any row to see the math.",
        "Same filings, different lens: discount projected free cash flow at the company's cost of capital, and check whether returns on capital beat that cost.",
        "Graham's central idea: only buy well below what the business is worth. The bar shows the market price against intrinsic value with 25% and 50% discount lines.",
    )
    Column(Modifier.fillMaxSize().background(VL.background)) {
        Column(Modifier.weight(1f).verticalScroll(rememberScrollState()).padding(20.dp)) {
            Text("STEP ${page + 1} OF 4", style = MaterialTheme.typography.labelSmall, color = VL.value)
            Text(titles[page], style = MaterialTheme.typography.headlineSmall, color = VL.textPrimary, modifier = Modifier.padding(vertical = 6.dp))
            Text(blurbs[page], color = VL.textSecondary, modifier = Modifier.padding(bottom = 14.dp))
            when (page) {
                0 -> Card {
                    val keys = listOf("revenue" to "Revenue", "net_income" to "Net income", "eps_diluted" to "Diluted EPS", "cfo" to "Cash from operations", "fcf" to "Free cash flow", "equity" to "Shareholders' equity", "cash" to "Cash & equivalents", "total_debt" to "Total debt")
                    keys.forEachIndexed { i, (k, label) ->
                        r.snapshot[k]?.let { sv ->
                            Column(Modifier.padding(vertical = 8.dp)) {
                                Row { Text(label, color = VL.textPrimary, modifier = Modifier.weight(1f)); Text(if (k == "eps_diluted") Fmt.money(sv.value) else Fmt.compact(sv.value), color = VL.textPrimary) }
                                Text("${sv.tag} · ${sv.form} · ${sv.periodEnd}", fontSize = 11.sp, color = VL.textTertiary, maxLines = 1)
                            }
                            if (i < keys.lastIndex) ThinDivider()
                        }
                    }
                }
                1 -> Card { listOf("graham_g", "graham_revised", "owner_earnings", "owner_earnings_per_share", "oe_value_hurdle").mapNotNull { r.modelA.metric(it) }.forEach { MetricRow(it) } }
                2 -> Column {
                    ModelToggle(model) { model = it }
                    Spacer(Modifier.height(12.dp))
                    val res = r.result(model)
                    Card {
                        Text(res.name, style = MaterialTheme.typography.bodySmall, color = VL.textSecondary)
                        Row(Modifier.padding(vertical = 8.dp)) { Text("Intrinsic value", color = VL.textPrimary, modifier = Modifier.weight(1f)); Text(Fmt.money(res.intrinsicValuePerShare), color = VL.value, fontSize = 20.sp, fontWeight = FontWeight.Bold) }
                        ThinDivider()
                        (if (model == ValuationModel.A) listOf("graham_revised", "oe_value_hurdle") else listOf("wacc", "dcf_perpetuity", "roic")).mapNotNull { res.metric(it) }.forEach { MetricRow(it) }
                    }
                    Text("Try the toggle. Notice how the two lenses disagree — that disagreement is information, not error.", style = MaterialTheme.typography.bodySmall, color = VL.textTertiary, modifier = Modifier.padding(top = 10.dp))
                }
                else -> Column {
                    Card { MarginOfSafetyView(r.modelA.marginOfSafety) }
                    Spacer(Modifier.height(12.dp))
                    Card {
                        Text("How to read it", style = MaterialTheme.typography.titleMedium, color = VL.textPrimary)
                        Text("● Amber dot: what the market charges today.", color = VL.price, modifier = Modifier.padding(top = 6.dp))
                        Text("╱ Mint line: what the filings say the business is worth.", color = VL.value, modifier = Modifier.padding(top = 4.dp))
                        Text("The two ticks mark 25% and 50% discounts. Value investors wait for the amber dot to fall left of a tick — the deeper, the safer.", style = MaterialTheme.typography.bodySmall, color = VL.textSecondary, modifier = Modifier.padding(top = 8.dp))
                        Text(r.modelA.marginOfSafety.formula, fontFamily = Mono, fontSize = 12.sp, color = VL.info, modifier = Modifier.padding(top = 8.dp))
                    }
                }
            }
            Row(Modifier.fillMaxWidth().padding(top = 16.dp), horizontalArrangement = Arrangement.Center) {
                repeat(4) { i -> Text(if (i == page) "●" else "○", color = if (i == page) VL.textPrimary else VL.textTertiary, modifier = Modifier.padding(horizontal = 3.dp)) }
            }
        }
        Row(Modifier.fillMaxWidth().background(VL.surface).padding(20.dp), verticalAlignment = Alignment.CenterVertically) {
            if (page > 0) TextButton({ page-- }) { Text("Back", color = VL.accent) }
            Spacer(Modifier.weight(1f))
            if (page < 3) PrimaryButtonSmall("Next") { page++ } else PrimaryButtonSmall("Finish & add to watchlist", onFinish)
        }
    }
}

@Composable
fun PrimaryButtonSmall(title: String, onClick: () -> Unit) {
    androidx.compose.material3.Button(onClick = onClick, colors = androidx.compose.material3.ButtonDefaults.buttonColors(containerColor = VL.value, contentColor = VL.background)) { Text(title, fontWeight = FontWeight.SemiBold) }
}

/** Step 2: "what kind of investor are you?" — asked once, changeable any time in Settings. */
@Composable
fun LensChoiceScreen(state: AppState, onBack: () -> Unit, onContinue: () -> Unit) {
    val lenses = remember { com.swcsoftware.valuelens.core.Grading.lenses() }
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)) {
        TextButton(onBack) { Text("‹ Back", color = VL.accent) }
        Text("What kind of investor are you?", style = MaterialTheme.typography.headlineSmall,
             color = VL.textPrimary, modifier = Modifier.padding(top = 8.dp))
        // It must say plainly that this changes no valuation (Track D).
        Text("This sets the bar we grade a business against — nothing else. Fair value, margin of safety and the verdict are worked out the same way whichever you pick, and you can change this any time in Settings.",
             color = VL.textSecondary, modifier = Modifier.padding(top = 10.dp, bottom = 20.dp))
        LensPicker(state.investorLens, { state.updateInvestorLens(it); onContinue() }, cards = true)
        // Quoted as-is from the live rules: the text opens with the grade letter.
        if (lenses.size == 2) {
            Text("Example — revenue growth for an operating company. ${lenses[0].name}: ${lenses[0].growthRule}. ${lenses[1].name}: ${lenses[1].growthRule}. The company's growth rate is the same number either way.",
                 style = MaterialTheme.typography.bodySmall, color = VL.textTertiary, modifier = Modifier.padding(top = 16.dp))
        }
    }
}

