import SwiftUI

struct OnboardingFlow: View {
    @Environment(AppSettings.self) private var settings
    @State private var path: [Step] = []

    enum Step: Hashable { case caseStudy }

    var body: some View {
        NavigationStack(path: $path) {
            IdentityView { identity in
                settings.identity = identity
                path.append(.caseStudy)
            }
            .navigationDestination(for: Step.self) { step in
                switch step {
                case .caseStudy: CaseStudyView()
                }
            }
        }
    }
}

/// Step 1: capture Full Name + Email — SEC requires this identity on every EDGAR request.
struct IdentityView: View {
    @Environment(AppSettings.self) private var settings
    let onContinue: (SECIdentity) -> Void
    @State private var name = ""
    @State private var email = ""

    private var identity: SECIdentity { SECIdentity(fullName: name, email: email) }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 28) {
                VStack(alignment: .leading, spacing: 8) {
                    Text("ValueLens").font(.vlDisplay).foregroundStyle(Theme.textPrimary)
                    Text("Intrinsic value from primary SEC disclosures.\nNo charts. No momentum. No noise.")
                        .font(.vlBody).foregroundStyle(Theme.textSecondary)
                }
                .padding(.top, 40)

                Card {
                    VStack(alignment: .leading, spacing: 14) {
                        Label("Identify yourself to SEC EDGAR", systemImage: "person.text.rectangle")
                            .font(.vlHeadline).foregroundStyle(Theme.textPrimary)
                        Text("SEC's fair-access policy requires every request to declare who is asking. Your name and email are stored in the device Keychain and sent only as the EDGAR User-Agent header.")
                            .font(.caption).foregroundStyle(Theme.textSecondary)
                        TextField("Full name", text: $name)
                            .textContentType(.name)
                            .textFieldStyle(.roundedBorder)
                        TextField("Email address", text: $email)
                            .textContentType(.emailAddress)
                            .keyboardType(.emailAddress)
                            .textInputAutocapitalization(.never)
                            .autocorrectionDisabled()
                            .textFieldStyle(.roundedBorder)
                        Text("User-Agent: \(identity.isValid ? identity.userAgent : "Jane Doe jane@example.com")")
                            .font(.vlMono).foregroundStyle(Theme.textTertiary)
                    }
                }

                PrimaryButton(title: "Continue to guided valuation", enabled: identity.isValid) {
                    onContinue(identity)
                }
                Text("Generated by ValueLens • Built on Pure Fundamental SEC EDGAR Disclosures • Not Financial Advice")
                    .font(.caption2).foregroundStyle(Theme.textTertiary).multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity)
            }
            .padding(20)
        }
        .background(Theme.background)
        .onAppear {
            if let id = settings.identity { name = id.fullName; email = id.email }
        }
    }
}
