"""Orchestrates: EDGAR -> normalize -> Model A + Model B -> serializable report."""
from __future__ import annotations

from datetime import date, datetime, timezone

from ..config import settings
from ..edgar.client import EdgarClient
from ..edgar.companyfacts import fetch_companyfacts
from ..edgar.identity import find_predecessor, no_annual_data_reason, profile
from ..edgar.tickers import resolve_ticker
from ..errors import NoAnnualData
from ..normalize.statements import NormalizedFinancials, growth_summary, normalize
from ..providers.prices import get_quote
from ..providers.rates import get_rates
from .model_a import run_model_a
from .model_b import run_model_b
from .types import Assumptions

DISCLAIMER = "Generated by Alpha • Built on Pure Fundamental SEC EDGAR Disclosures • Not Financial Advice"


async def load_financials(ticker: str, user_agent: str | None) -> NormalizedFinancials:
    client = EdgarClient(user_agent)
    ref = await resolve_ticker(client, ticker)
    try:
        fin = normalize(await fetch_companyfacts(client, ref))
    except NoAnnualData:
        raise NoAnnualData(no_annual_data_reason(ref.ticker, await profile(client, ref.cik)), {"ticker": ref.ticker, "cik": ref.cik})
    if not fin.annual:
        # Successor-issuer fallback (holding-company reorganizations); never reached for ordinary filers.
        prof = await profile(client, ref.cik)
        pred = await find_predecessor(client, ref, date.today(), prof)
        if pred is not None:
            pf = normalize(await fetch_companyfacts(client, pred.ref))
            if pf.annual:
                note = (f"Filings come from predecessor {pred.ref.name} (CIK {pred.ref.cik}); {ref.ticker} is now "
                        f"{pred.successor_name} (CIK {ref.cik}, first filing {pred.successor_first_filing or 'n/a'}"
                        + (", successor notice 8-K12B" if pred.via_successor_notice else "") + ").")
                pf.ticker, pf.warnings = ref.ticker, [note] + pf.warnings
                return pf
        raise NoAnnualData(
            no_annual_data_reason(ref.ticker, prof),
            {"ticker": ref.ticker, "cik": ref.cik, "warnings": fin.warnings},
        )
    return fin


def financials_payload(fin: NormalizedFinancials) -> dict:
    return {
        "company": {"ticker": fin.ticker, "cik": fin.cik, "name": fin.name},
        "annual": [p.to_dict() for p in fin.annual],
        "ttm": fin.ttm.to_dict() if fin.ttm else None,
        "current_shares": fin.current_shares.to_dict() if fin.current_shares else None,
        "growth": growth_summary(fin),
        "warnings": fin.warnings,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


async def build_assumptions(overrides: dict[str, float | None]) -> Assumptions:
    rates = await get_rates()
    def pick(name: str, default: float) -> float:
        v = overrides.get(name)
        return float(v) if v is not None else default
    return Assumptions(
        aaa_yield_pct=pick("aaa_yield_pct", rates.aaa_yield_pct),
        treasury_10y_pct=pick("treasury_10y_pct", rates.treasury_10y_pct),
        hurdle_rate_pct=pick("hurdle_rate_pct", settings.default_hurdle_rate_pct),
        equity_risk_premium_pct=pick("equity_risk_premium_pct", settings.default_equity_risk_premium_pct),
        beta=pick("beta", settings.default_beta),
        terminal_growth_pct=pick("terminal_growth_pct", settings.default_terminal_growth_pct),
        exit_multiple=pick("exit_multiple", settings.default_exit_multiple),
        tax_rate_pct=pick("tax_rate_pct", settings.default_tax_rate_pct),
        rate_source=rates.source if not any(overrides.get(k) is not None for k in ("aaa_yield_pct", "treasury_10y_pct")) else f"{rates.source} + user override",
    )


async def build_valuation(ticker: str, user_agent: str | None, overrides: dict[str, float | None],
                          price_override: float | None) -> dict:
    fin = await load_financials(ticker, user_agent)
    assumptions = await build_assumptions(overrides)
    quote = await get_quote(fin.ticker, price_override)
    price = quote.price if quote else None
    model_a = run_model_a(fin, assumptions, price)
    model_b = run_model_b(fin, assumptions, price)
    ttm = fin.ttm
    snapshot = {}
    if ttm:
        for k in ("revenue", "net_income", "eps_diluted", "cfo", "fcf", "owner_earnings", "equity", "cash",
                  "total_debt", "total_liabilities", "roic", "roe", "current_ratio", "debt_to_equity",
                  "operating_margin", "net_margin", "book_value_per_share"):
            if k in ttm.values:
                snapshot[k] = ttm.values[k].to_dict()
    history = [
        {"fiscal_year": p.fiscal_year, "period_end": p.period_end.isoformat(),
         **{k: p.get(k) for k in ("revenue", "net_income", "eps_diluted", "fcf", "owner_earnings", "equity",
                                   "roic", "book_value_per_share", "cfo", "capex")}}
        for p in fin.annual
    ]
    return {
        "company": {"ticker": fin.ticker, "cik": fin.cik, "name": fin.name},
        "quote": quote.to_dict() if quote else None,
        "assumptions": assumptions.to_dict(),
        "snapshot": snapshot,
        "history": history,
        "growth": growth_summary(fin),
        "model_a": model_a,
        "model_b": model_b,
        "warnings": fin.warnings,
        "disclaimer": DISCLAIMER,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
